# Generated by Django 5.1.4 on 2026-06-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ('-created_at', '-id')},
        ),
    ]
