# Generated by Django 5.1.4 on 2026-06-25 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_alter_auditlog_options'),
        ('tenants', '0002_tenant_address_tenant_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
    ]
