# Generated by Django 5.1.4 on 2026-06-26 17:00

from django.conf import settings
from django.db import migrations, models


def seed_singleton(apps, schema_editor):
    RuntimeConfig = apps.get_model('governance', 'RuntimeConfig')
    RuntimeConfig.objects.get_or_create(
        pk=1, defaults={'mode': 'dev' if settings.DEBUG else 'prod'}
    )


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0003_alter_auditlog_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('dev', 'Development'), ('prod', 'Production')], default='dev', max_length=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(seed_singleton, migrations.RunPython.noop),
    ]
