# Generated by Django 5.1.4 on 2026-10-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0005_alter_auditlog_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtimeconfig',
            name='idsr_deadline_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text='Hours to notify an immediately-notifiable case before it is overdue.'),
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='surveillance_min_cases',
            field=models.PositiveSmallIntegerField(default=3, help_text='Cases in a day before a disease spike can alarm.'),
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='surveillance_z_threshold',
            field=models.FloatField(default=2.0, help_text='Std-devs above the daily baseline that count as a spike.'),
        ),
    ]
