# Generated by Django 5.1.4 on 2026-09-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_normalize_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='prescriber',
        ),
    ]
