# Generated by Django 5.1.4 on 2026-06-25 08:29

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phone_login'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
