# Generated by Django 5.1.4 on 2026-06-25 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Nigerian phone number (e.g. 08031234567 or +2348031234567).', regex='^(?:\\+234|0)[789]\\d{9}$')]),
        ),
    ]
