# Generated by Django 5.1.4 on 2026-09-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('tenant_admin', 'Tenant Admin'), ('doctor', 'Doctor'), ('pharmacist', 'Pharmacist'), ('nurse', 'Nurse'), ('midwife', 'Midwife'), ('chew', 'Community Health Extension Worker'), ('public', 'Public')], default='public', max_length=20),
        ),
    ]
