# Generated by Django 5.1.4 on 2026-09-07 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_license_number_alter_user_role'),
        ('pharmacy', '0010_preauthorization_reopened_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hmo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='pharmacy.hmo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('tenant_admin', 'Tenant Admin'), ('doctor', 'Doctor'), ('pharmacist', 'Pharmacist'), ('nurse', 'Nurse'), ('midwife', 'Midwife'), ('chew', 'Community Health Extension Worker'), ('hmo', 'HMO / Insurer'), ('government', 'Government Health Authority'), ('public', 'Public')], default='public', max_length=20),
        ),
    ]
