# Generated by Django 5.1.4 on 2026-09-07 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_hmo_alter_user_role'),
        ('tenants', '0007_tenant_idle_logout_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jurisdiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='tenants.jurisdiction'),
        ),
    ]
