# Generated by Django 5.1.4 on 2026-09-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privileges',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
