# Generated by Django 5.1.4 on 2026-09-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_normalize_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('tenant_admin', 'Tenant Admin'), ('doctor', 'Doctor'), ('pharmacist', 'Pharmacist'), ('nurse', 'Nurse'), ('midwife', 'Midwife'), ('chew', 'Community Health Extension Worker'), ('receptionist', 'Receptionist / Records Officer'), ('hmo', 'HMO / Insurer'), ('government', 'Government Health Authority'), ('public', 'Public')], default='public', max_length=20),
        ),
    ]
