# Generated by Django 5.1.4 on 2026-10-07 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_role_receptionist'),
        ('hmos', '0001_initial'),
    ]

    operations = [
        # State only: the table is still pharmacy_hmo; no DB change.
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.AlterField(
                model_name='user',
                name='hmo',
                field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='hmos.hmo'),
            ),
        ]),
    ]
