"""Nigeria states + LGAs — canonical server copy used to validate the report
`region` field and to roll reports up by state.

Data lives in ``nigeria_states.json``, generated by scripts/gen_nigeria.py from
``apps.tenants.ng_jurisdiction`` — the same list that seeds the Jurisdiction
tree the web picker reads, and the same one the Flutter picker is generated
from, so a spelling this rejects is one no picker can offer. Region is stored
as "LGA, State".
"""
import json
from functools import lru_cache
from pathlib import Path

from rest_framework import serializers

_JSON = Path(__file__).with_name("nigeria_states.json")


@lru_cache(maxsize=1)
def states():
    """{state: [lga, ...]} loaded once."""
    return json.loads(_JSON.read_text(encoding="utf-8"))


@lru_cache(maxsize=1)
def valid_regions():
    """Set of every accepted "LGA, State" string."""
    return {f"{lga}, {st}" for st, lgas in states().items() for lga in lgas}


def region_state(region):
    """State portion of a "LGA, State" region, or "" if unparseable."""
    return region.rsplit(", ", 1)[-1] if ", " in region else ""


def validate_region(value):
    # Optional. If supplied, must be a known "LGA, State" from the Nigeria list.
    if value and value not in valid_regions():
        raise serializers.ValidationError(
            "Not a valid Nigerian LGA, State. Pick from the list."
        )
    return value
