# Generated by Django 5.1.4 on 2026-09-12 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0018_canonical_region_spellings'),
        ('prescriptions', '0002_normalize_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribercommission',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriber_commissions', to='analytics.prescription'),
        ),
        migrations.AlterField(
            model_name='prescribercommission',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='prescriptions.prescription'),
        ),
    ]
