# Generated by Django 5.1.4 on 2026-09-13 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0019_consultation_band_on_drug_order'),
        ('prescriptions', '0003_commission_on_drug_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationpayout',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_payouts', to='analytics.prescription'),
        ),
        migrations.AlterField(
            model_name='consultationpayout',
            name='prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_payout', to='prescriptions.prescription'),
        ),
    ]
