# Generated by Django 5.1.4 on 2026-09-26 20:20

from django.db import migrations


class Migration(migrations.Migration):
    """Drop the pharmacy's own prescriber registry: the doctors and hospitals
    it kept, the commissions and consultation payouts it owed them, and the
    consultation band a script carried. Whole tables go with DeleteModel, so
    no index is left naming a column that is already gone."""

    dependencies = [
        ('customers', '0004_drop_customer_prescriber'),
        ('prescriptions', '0005_script_phone_from_record'),
    ]

    operations = [
        migrations.RemoveField(model_name='prescription', name='prescriber'),
        migrations.RemoveField(model_name='prescription', name='consultation_category'),
        migrations.RemoveField(model_name='prescription', name='consultation_fee'),
        migrations.DeleteModel(name='ConsultationPayout'),
        migrations.DeleteModel(name='PrescriberCommission'),
        migrations.DeleteModel(name='Prescriber'),
        migrations.DeleteModel(name='Hospital'),
    ]
