# Generated by Django 5.1.4 on 2026-06-25 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_address_tenant_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('local', 'Local'), ('state', 'State'), ('national', 'National')], max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='tenants.jurisdiction')),
            ],
        ),
        migrations.AddField(
            model_name='tenant',
            name='jurisdiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='tenants.jurisdiction'),
        ),
        migrations.AddIndex(
            model_name='jurisdiction',
            index=models.Index(fields=['level'], name='tenants_jur_level_e5309c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jurisdiction',
            unique_together={('name', 'level', 'parent')},
        ),
    ]
