# Generated by Django 5.1.4 on 2026-06-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_jurisdiction_tenant_jurisdiction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='subscription_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
    ]
