# Generated by Django 5.1.4 on 2026-09-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_seed_nigeria_jurisdiction'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='kind',
            field=models.CharField(choices=[('pharmacy', 'Pharmacy'), ('hospital', 'Hospital')], db_index=True, default='pharmacy', max_length=20),
        ),
    ]
