# Generated by Django 5.1.4 on 2026-09-06 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='idle_logout_minutes',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(1440)]),
        ),
    ]
