# Generated by Django 5.1.4 on 2026-09-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_tenant_idle_logout_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.TextField(blank=True),
        ),
    ]
