# Generated by Django 5.1.4 on 2026-10-07 16:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0008_tenant_logo_data_url'),
    ]

    operations = [
        # State only: the table is still pharmacy_hmo; no DB change.
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.CreateModel(
                name='HMO',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('created_at', models.DateTimeField(auto_now_add=True)),
                    ('updated_at', models.DateTimeField(auto_now=True)),
                    ('name', models.CharField(max_length=200)),
                    ('code', models.CharField(blank=True, max_length=50)),
                    ('contact', models.CharField(blank=True, max_length=200)),
                    ('email', models.EmailField(blank=True, max_length=254)),
                    ('coverage_percent', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5)),
                    ('auto_submit_claims', models.BooleanField(default=False)),
                    ('preauth_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                    ('is_active', models.BooleanField(default=True)),
                    ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ],
                options={
                    'verbose_name': 'HMO',
                    'db_table': 'pharmacy_hmo',
                    'ordering': ('name', 'id'),
                    'unique_together': {('tenant', 'name')},
                },
            ),
        ]),
    ]
