# Generated by Django 5.1.4 on 2026-09-04 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('pharmacy', '0004_tillsession_salepayment_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Supplier',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(max_length=200)),
                        ('contact_person', models.CharField(blank=True, max_length=200)),
                        ('phone', models.CharField(blank=True, max_length=30)),
                        ('email', models.EmailField(blank=True, max_length=254)),
                        ('address', models.TextField(blank=True)),
                        ('is_active', models.BooleanField(default=True)),
                        ('notes', models.TextField(blank=True)),
                        ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                    ],
                    options={
                        'ordering': ('name', 'id'),
                        'indexes': [models.Index(fields=['tenant', 'is_active'], name='pharmacy_su_tenant__ec193e_idx')],
                        'constraints': [],
                        'unique_together': {('tenant', 'name')},
                        'db_table': 'pharmacy_supplier',
                    },
                ),
                migrations.CreateModel(
                    name='StockItem',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(max_length=255)),
                        ('sku', models.CharField(blank=True, max_length=50)),
                        ('form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('cream', 'Cream'), ('drops', 'Drops'), ('consumable', 'Consumable'), ('other', 'Other')], default='tablet', max_length=20)),
                        ('unit', models.CharField(default='unit', max_length=50)),
                        ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('reorder_level', models.PositiveIntegerField(default=0)),
                        ('prescription_only', models.BooleanField(default=False)),
                        ('is_active', models.BooleanField(default=True)),
                        ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='catalog.medication')),
                        ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                    ],
                    options={
                        'ordering': ('name', 'id'),
                        'indexes': [models.Index(fields=['tenant', 'name'], name='pharmacy_st_tenant__ff1b58_idx'), models.Index(fields=['tenant', 'is_active'], name='pharmacy_st_tenant__04c5ed_idx')],
                        'constraints': [models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('tenant', 'sku'), name='pharmacy_stockitem_unique_sku_per_tenant')],
                        'db_table': 'pharmacy_stockitem',
                    },
                ),
                migrations.CreateModel(
                    name='StockBatch',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('batch_number', models.CharField(max_length=100)),
                        ('expiry_date', models.DateField(blank=True, null=True)),
                        ('quantity', models.PositiveIntegerField(default=0)),
                        ('quantity_received', models.PositiveIntegerField(default=0)),
                        ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('received_at', models.DateField(blank=True, null=True)),
                        ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                        ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.stockitem')),
                        ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.supplier')),
                    ],
                    options={
                        'ordering': ('expiry_date', 'id'),
                        'indexes': [models.Index(fields=['tenant', 'item'], name='pharmacy_st_tenant__92e32d_idx'), models.Index(fields=['tenant', 'expiry_date'], name='pharmacy_st_tenant__875300_idx')],
                        'constraints': [],
                        'unique_together': {('tenant', 'item', 'batch_number')},
                        'db_table': 'pharmacy_stockbatch',
                    },
                ),
                migrations.CreateModel(
                    name='StockMovement',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('kind', models.CharField(choices=[('receipt', 'Receipt'), ('dispense', 'Dispense'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('write_off', 'Write Off')], max_length=20)),
                        ('quantity', models.IntegerField()),
                        ('reason', models.CharField(blank=True, max_length=255)),
                        ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.stockbatch')),
                        ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stockitem')),
                        ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                        ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'ordering': ('-created_at', '-id'),
                        'indexes': [models.Index(fields=['tenant', 'created_at'], name='pharmacy_st_tenant__049b4c_idx'), models.Index(fields=['tenant', 'item', 'kind'], name='pharmacy_st_tenant__49248f_idx')],
                        'constraints': [],
                        'db_table': 'pharmacy_stockmovement',
                    },
                ),
            ],
        ),
    ]
