# Generated by Django 5.1.4 on 2026-09-04 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('catalog', '0006_alter_article_tenant_alter_disease_tenant_and_more'),
        ('inventory', '0002_stockmovement_sale'),
        ('tenants', '0005_seed_nigeria_jurisdiction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale')], default='retail', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='StockCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_quantity', models.IntegerField(default=0)),
                ('actual_quantity', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('adjusted', 'Adjusted')], default='pending', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_quantity', models.PositiveIntegerField(default=1)),
                ('approved_quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('received', 'Received')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AlterModelOptions(
            name='stockbatch',
            options={'ordering': ('expiry_date', 'id'), 'verbose_name_plural': 'stock batches'},
        ),
        migrations.RemoveIndex(
            model_name='supplier',
            name='pharmacy_su_tenant__ec193e_idx',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='barcode_type',
            field=models.CharField(blank=True, choices=[('UPC', 'Upc'), ('EAN13', 'EAN-13'), ('CODE128', 'Code 128'), ('QR', 'QR code'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch holding this line. Blank means tenant-wide.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='brand',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='gtin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='store',
            field=models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale')], default='retail', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='form',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('infusion', 'Infusion'), ('inhaler', 'Inhaler'), ('suspension', 'Suspension'), ('solution', 'Solution'), ('cream', 'Cream'), ('paste', 'Paste'), ('patch', 'Patch'), ('galenical', 'Galenical'), ('drops', 'Drops'), ('eye_drop', 'Eye drop'), ('ear_drop', 'Ear drop'), ('eye_ointment', 'Eye ointment'), ('rectal', 'Rectal'), ('vaginal', 'Vaginal'), ('consumable', 'Consumable'), ('detergent', 'Detergent'), ('soap', 'Soap'), ('drink', 'Drink'), ('table_water', 'Table water'), ('food_item', 'Food item'), ('biscuit', 'Biscuit'), ('sweet', 'Sweet'), ('other', 'Other')], default='tablet', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='kind',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('dispense', 'Dispense'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('write_off', 'Write Off'), ('transfer', 'Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['tenant', 'store'], name='pharmacy_st_tenant__163b11_idx'),
        ),
        migrations.AddField(
            model_name='stockcheck',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockcheck',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_checks', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='stockcheck',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockcheck',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='stockcheckitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_check_lines', to='inventory.stockitem'),
        ),
        migrations.AddField(
            model_name='stockcheckitem',
            name='stock_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockcheck'),
        ),
        migrations.AddField(
            model_name='stockcheckitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='from_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='inventory.stockitem'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='to_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='inventory.stockitem'),
        ),
        migrations.AddIndex(
            model_name='stockcheck',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='inventory_s_tenant__2a679e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockcheckitem',
            index=models.Index(fields=['tenant', 'item'], name='inventory_s_tenant__140d09_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockcheckitem',
            unique_together={('stock_check', 'item')},
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='inventory_t_tenant__acc82f_idx'),
        ),
    ]
