# Generated by Django 5.1.4 on 2026-09-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockcheck_stockcheckitem_transferrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='is_controlled',
            field=models.BooleanField(default=False, help_text='Controlled (poison) drug — prescribing and dispensing is reported to the state.'),
        ),
    ]
