# Generated by Django 5.1.4 on 2026-09-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockitem_is_controlled'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockitem',
            name='pharmacy_stockitem_unique_sku_per_tenant',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='barcode_type',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='gtin',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='sku',
        ),
    ]
