# Generated by Django 5.1.4 on 2026-08-11 18:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_alter_article_tenant_alter_disease_tenant_and_more'),
        ('tenants', '0005_seed_nigeria_jurisdiction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital_number', models.CharField(blank=True, max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Nigerian phone number (e.g. 08031234567 or +2348031234567).', regex='^(?:\\+234|0)[789]\\d{9}$')])),
                ('address', models.TextField(blank=True)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A Pos'), ('A-', 'A Neg'), ('B+', 'B Pos'), ('B-', 'B Neg'), ('AB+', 'Ab Pos'), ('AB-', 'Ab Neg'), ('O+', 'O Pos'), ('O-', 'O Neg')], max_length=5)),
                ('genotype', models.CharField(blank=True, choices=[('AA', 'Aa'), ('AS', 'As'), ('AC', 'Ac'), ('SS', 'Ss'), ('SC', 'Sc')], max_length=5)),
                ('allergies', models.TextField(blank=True)),
                ('nhis_number', models.CharField(blank=True, max_length=50)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=200)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=20)),
                ('next_of_kin_relationship', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deceased', 'Deceased')], default='active', max_length=20)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('chronic_conditions', models.ManyToManyField(blank=True, related_name='patients', to='catalog.disease')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ('last_name', 'first_name', 'id'),
                'indexes': [models.Index(fields=['tenant', 'last_name'], name='patients_pa_tenant__ac2fb1_idx'), models.Index(fields=['tenant', 'status'], name='patients_pa_tenant__ca9a97_idx'), models.Index(fields=['tenant', 'phone'], name='patients_pa_tenant__bdfc4d_idx')],
                'unique_together': {('tenant', 'hospital_number')},
            },
        ),
    ]
