# Generated by Django 5.1.4 on 2026-08-12 20:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_article_tenant_alter_disease_tenant_and_more'),
        ('patients', '0002_patientaccesslog'),
        ('tenants', '0005_seed_nigeria_jurisdiction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('nhia', 'NHIA'), ('private', 'Private Pay'), ('insurance', 'Private Insurance'), ('corporate', 'Corporate'), ('staff', 'Staff'), ('dependant', 'Dependant'), ('emergency', 'Emergency'), ('retainership', 'Retainership')], default='regular', max_length=15),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['tenant', 'patient_type'], name='patients_pa_tenant__7845a4_idx'),
        ),
    ]
