# Generated by Django 5.1.4 on 2026-08-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_patient_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientaccesslog',
            name='action',
            field=models.CharField(choices=[('list', 'List'), ('retrieve', 'Retrieve'), ('history', 'History'), ('delete', 'Delete')], max_length=20),
        ),
    ]
