# Generated by Django 5.1.4 on 2026-08-13 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_date_of_death_alter_patientaccesslog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deceased', 'Deceased'), ('merged', 'Merged')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientaccesslog',
            name='action',
            field=models.CharField(choices=[('list', 'List'), ('retrieve', 'Retrieve'), ('history', 'History'), ('delete', 'Delete'), ('merge', 'Merge')], max_length=20),
        ),
    ]
