# Generated by Django 5.1.4 on 2026-09-04 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_merged_into_alter_patient_status_and_more'),
        ('tenants', '0005_seed_nigeria_jurisdiction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='patientaccesslog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
    ]
