# Generated by Django 5.1.4 on 2026-09-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patient_tenant_alter_patientaccesslog_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientaccesslog',
            name='action',
            field=models.CharField(choices=[('list', 'List'), ('retrieve', 'Retrieve'), ('history', 'History'), ('lookup', 'Lookup'), ('delete', 'Delete'), ('merge', 'Merge')], max_length=20),
        ),
    ]
