# Generated by Django 5.1.4 on 2026-09-20 17:07

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patient_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'default_manager_name': 'all_objects', 'ordering': ('last_name', 'first_name', 'id')},
        ),
        migrations.AlterModelManagers(
            name='patient',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
