"""Regenerate every copy of the Nigeria state/LGA list from the one source.

    python scripts/gen_nigeria.py

``apps/tenants/ng_jurisdiction.py`` (the INEC list) is the source of truth: it
seeds the Jurisdiction tree, which is what the web picker reads. This script
writes the two derived copies from it:

  * ``apps/analytics/nigeria_states.json`` — what the serializer validates
    ``region`` against.
  * ``mobile/lib/nigeria_data.dart`` — what the Flutter picker offers. Kept as
    a compile-time constant rather than an API call so a CHW can still file a
    report with no signal.

Both are checked into the repository, and tests/test_region.py fails if either
has drifted, so nobody has to remember to run this — the test says when.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from apps.tenants.ng_jurisdiction import NG_STATES_LGAS  # noqa: E402

JSON_PATH = ROOT / "apps" / "analytics" / "nigeria_states.json"
DART_PATH = ROOT / "mobile" / "lib" / "nigeria_data.dart"

DART_HEADER = """// GENERATED by scripts/gen_nigeria.py from apps/tenants/ng_jurisdiction.py.
// Do not edit by hand: tests/test_region.py fails when this drifts from the
// source, and a hand-fixed spelling here is one the server will reject.
//
// Nigeria states -> their Local Government Areas (INEC list). Source for the
// `region` field on case reports and ADRs, stored as "LGA, State".
// ponytail: a constant, not an API call — the picker has to work in a village
// with no signal. Regenerate when the source list changes; that is all.

const Map<String, List<String>> nigeriaStates = {
"""


def dart_string(value):
    """`value` as a Dart string literal, single-quoted unless it holds one."""
    if "'" in value:
        return '"%s"' % value.replace('"', '\\"')
    return "'%s'" % value


def dart_source():
    lines = [DART_HEADER]
    for state, lgas in sorted(NG_STATES_LGAS.items()):
        joined = ", ".join(dart_string(lga) for lga in lgas)
        lines.append("  %s: [%s],\n" % (dart_string(state), joined))
    lines.append("};\n")
    return "".join(lines)


def json_source():
    ordered = {state: NG_STATES_LGAS[state] for state in sorted(NG_STATES_LGAS)}
    return json.dumps(ordered, ensure_ascii=False, indent=2, sort_keys=False) + "\n"


def main():
    JSON_PATH.write_text(json_source(), encoding="utf-8")
    DART_PATH.write_text(dart_source(), encoding="utf-8")
    total = sum(len(v) for v in NG_STATES_LGAS.values())
    print("wrote %s and %s (%d states, %d LGAs)" % (
        JSON_PATH.relative_to(ROOT), DART_PATH.relative_to(ROOT),
        len(NG_STATES_LGAS), total,
    ))


if __name__ == "__main__":
    main()
