# Generated by Django 5.1.4 on 2026-09-04 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_contentembedding_tenant'),
        ('tenants', '0005_seed_nigeria_jurisdiction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentembedding',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
    ]
