# Generated by Django 5.1.4 on 2026-09-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmo',
            name='auto_submit_claims',
            field=models.BooleanField(default=False),
        ),
    ]
