# Generated by Django 5.1.4 on 2026-09-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_hmo_auto_submit_claims'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount_tendered',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
