# Generated by Django 5.1.4 on 2026-09-06 14:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockcheck_stockcheckitem_transferrequest_and_more'),
        ('pharmacy', '0006_alter_claimbatch_options_alter_claim_tenant_and_more'),
        ('tenants', '0007_tenant_idle_logout_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmo',
            name='preauth_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='hmoenrollment',
            name='annual_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='HmoItemRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coverage_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('hmo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_rules', to='pharmacy.hmo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hmo_rules', to='inventory.stockitem')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ('item__name', 'id'),
                'indexes': [models.Index(fields=['tenant', 'hmo'], name='pharmacy_hm_tenant__bd4bee_idx')],
                'unique_together': {('tenant', 'hmo', 'item')},
            },
        ),
        migrations.CreateModel(
            name='PreAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_approved', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('code', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('declined', 'Declined'), ('used', 'Used'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preauths', to='pharmacy.hmoenrollment')),
                ('hmo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preauths', to='pharmacy.hmo')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'pre-authorization',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['tenant', 'status', 'created_at'], name='pharmacy_pr_tenant__59b541_idx')],
                'unique_together': {('tenant', 'reference')},
            },
        ),
    ]
