# Generated by Django 5.1.4 on 2026-09-06 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockcheck_stockcheckitem_transferrequest_and_more'),
        ('pharmacy', '0007_hmo_preauth_threshold_hmoenrollment_annual_limit_and_more'),
        ('tenants', '0007_tenant_idle_logout_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreAuthorizationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_approved', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('declined', 'Declined')], default='requested', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('authorization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.preauthorization')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preauth_items', to='inventory.stockitem')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['tenant', 'authorization'], name='pharmacy_pr_tenant__dd3c84_idx')],
                'unique_together': {('authorization', 'item')},
            },
        ),
    ]
