# Generated by Django 5.1.4 on 2026-09-06 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_preauthorizationitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preauthorization',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preauth_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preauthorizationitem',
            name='quantity_approved',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
