# Generated by Django 5.1.4 on 2026-09-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_preauthorization_requested_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preauthorization',
            name='reopened_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
