# Generated by Django 5.1.4 on 2026-09-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_preauthorization_reopened_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmoitemrule',
            name='tariff',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
