# Generated by Django 5.1.4 on 2026-09-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_hmoitemrule_tariff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='batch',
        ),
        migrations.DeleteModel(
            name='ClaimBatch',
        ),
    ]
