# Generated by Django 5.1.4 on 2026-10-07 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_hmo'),
        ('hmos', '0001_initial'),
        ('pharmacy', '0013_schemedependent'),
    ]

    operations = [
        # State only: the table is still pharmacy_hmo; no DB change.
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.AlterField(
                model_name='hmoitemrule',
                name='hmo',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_rules', to='hmos.hmo'),
            ),
            migrations.AlterField(
                model_name='hmoenrollment',
                name='hmo',
                field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='hmos.hmo'),
            ),
            migrations.AlterField(
                model_name='claim',
                name='hmo',
                field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='hmos.hmo'),
            ),
            migrations.AlterField(
                model_name='preauthorization',
                name='hmo',
                field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preauths', to='hmos.hmo'),
            ),
            migrations.DeleteModel(
                name='HMO',
            ),
        ]),
    ]
