# Generated by Django 5.1.4 on 2026-06-23 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=20)),
                ('query', models.CharField(blank=True, max_length=500)),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'event_type', 'created_at'], name='analytics_a_tenant__22ad80_idx'), models.Index(fields=['tenant', 'object_type', 'object_id'], name='analytics_a_tenant__cc6f8b_idx')],
            },
        ),
    ]
