# Generated by Django 5.1.4 on 2026-06-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_aiinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinteraction',
            name='feedback',
            field=models.CharField(blank=True, choices=[('up', 'thumbs up'), ('down', 'thumbs down')], max_length=4),
        ),
    ]
