# Generated by Django 5.1.4 on 2026-06-24 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_aiinteraction_feedback'),
        ('catalog', '0002_fts_gin_indexes'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('critical', 'Critical')], default='mild', max_length=20)),
                ('outcome', models.CharField(choices=[('ongoing', 'Ongoing'), ('recovered', 'Recovered'), ('referred', 'Referred'), ('deceased', 'Deceased')], default='ongoing', max_length=20)),
                ('patient_age_group', models.CharField(blank=True, max_length=20)),
                ('patient_sex', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_reports', to='catalog.disease')),
                ('medications', models.ManyToManyField(blank=True, related_name='case_reports', to='catalog.medication')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('symptoms', models.ManyToManyField(blank=True, related_name='case_reports', to='catalog.symptom')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='analytics_c_tenant__bdfa95_idx'), models.Index(fields=['tenant', 'disease'], name='analytics_c_tenant__ee516b_idx')],
            },
        ),
    ]
