# Generated by Django 5.1.4 on 2026-06-25 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_casereport'),
        ('catalog', '0004_disease_notifiable'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdverseDrugReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reaction', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('life_threatening', 'Life Threatening')], default='mild', max_length=20)),
                ('outcome', models.CharField(choices=[('ongoing', 'Ongoing'), ('recovered', 'Recovered'), ('recovered_with_sequelae', 'Recovered Sequelae'), ('fatal', 'Fatal')], default='ongoing', max_length=25)),
                ('patient_age_group', models.CharField(blank=True, max_length=20)),
                ('patient_sex', models.CharField(blank=True, max_length=10)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='casereport',
            name='region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='casereport',
            index=models.Index(fields=['tenant', 'region'], name='analytics_c_tenant__0014a5_idx'),
        ),
        migrations.AddField(
            model_name='adversedrugreaction',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverse_reactions', to='catalog.medication'),
        ),
        migrations.AddField(
            model_name='adversedrugreaction',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adversedrugreaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='adversedrugreaction',
            index=models.Index(fields=['tenant', 'created_at'], name='analytics_a_tenant__804454_idx'),
        ),
        migrations.AddIndex(
            model_name='adversedrugreaction',
            index=models.Index(fields=['tenant', 'medication'], name='analytics_a_tenant__c58e3b_idx'),
        ),
    ]
