# Generated by Django 5.1.4 on 2026-06-26 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_alter_adversedrugreaction_tenant_and_more'),
        ('catalog', '0005_alter_article_tenant_alter_disease_tenant_and_more'),
        ('tenants', '0003_jurisdiction_tenant_jurisdiction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaccine', models.CharField(max_length=120)),
                ('dose_number', models.PositiveSmallIntegerField(default=1)),
                ('patient_age_group', models.CharField(blank=True, max_length=20)),
                ('patient_sex', models.CharField(blank=True, max_length=10)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='analytics_i_tenant__d40eac_idx'), models.Index(fields=['tenant', 'vaccine'], name='analytics_i_tenant__535504_idx')],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('flag', models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('organism', models.CharField(blank=True, max_length=120)),
                ('antibiotic', models.CharField(blank=True, max_length=120)),
                ('susceptibility', models.CharField(blank=True, choices=[('susceptible', 'Susceptible'), ('intermediate', 'Intermediate'), ('resistant', 'Resistant')], max_length=20)),
                ('patient_age_group', models.CharField(blank=True, max_length=20)),
                ('patient_sex', models.CharField(blank=True, max_length=10)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results', to='catalog.disease')),
                ('lab_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='catalog.labtest')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='analytics_l_tenant__988992_idx'), models.Index(fields=['tenant', 'organism'], name='analytics_l_tenant__55206c_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('on_hand', models.PositiveIntegerField(default=0)),
                ('consumed', models.PositiveIntegerField(default=0)),
                ('shortage', models.BooleanField(default=False)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reports', to='catalog.medication')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='analytics_s_tenant__164b83_idx'), models.Index(fields=['tenant', 'medication'], name='analytics_s_tenant__75662a_idx')],
            },
        ),
        migrations.CreateModel(
            name='VitalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('birth', 'Birth'), ('death', 'Death')], max_length=10)),
                ('maternal_death', models.BooleanField(default=False)),
                ('infant_death', models.BooleanField(default=False)),
                ('patient_age_group', models.CharField(blank=True, max_length=20)),
                ('patient_sex', models.CharField(blank=True, max_length=10)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('cause', models.ForeignKey(blank=True, help_text='Cause of death (deaths only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_events', to='catalog.disease')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['tenant', 'event_type', 'created_at'], name='analytics_v_tenant__81764e_idx'), models.Index(fields=['tenant', 'region'], name='analytics_v_tenant__99b532_idx')],
            },
        ),
    ]
