# Generated by Django 5.1.4 on 2026-06-26 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_immunization_labresult_stockreport_vitalevent'),
        ('catalog', '0005_alter_article_tenant_alter_disease_tenant_and_more'),
        ('tenants', '0003_jurisdiction_tenant_jurisdiction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('in_person', 'In Person'), ('telemedicine', 'Telemedicine')], default='in_person', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('patient_age_group', models.CharField(blank=True, max_length=20)),
                ('patient_sex', models.CharField(blank=True, max_length=10)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['tenant', 'mode', 'created_at'], name='analytics_a_tenant__991664_idx'), models.Index(fields=['tenant', 'status'], name='analytics_a_tenant__4f4ccc_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommunityHealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('pregnancy', 'Pregnancy'), ('newborn', 'Newborn'), ('malnutrition', 'Malnutrition'), ('death', 'Death'), ('other', 'Other')], max_length=20)),
                ('danger_signs', models.BooleanField(default=False)),
                ('referred', models.BooleanField(default=False)),
                ('patient_age_group', models.CharField(blank=True, max_length=20)),
                ('patient_sex', models.CharField(blank=True, max_length=10)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['tenant', 'report_type', 'created_at'], name='analytics_c_tenant__317f26_idx'), models.Index(fields=['tenant', 'region'], name='analytics_c_tenant__237db2_idx')],
            },
        ),
        migrations.CreateModel(
            name='FacilityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beds_total', models.PositiveIntegerField(default=0)),
                ('beds_occupied', models.PositiveIntegerField(default=0)),
                ('avg_wait_minutes', models.PositiveIntegerField(default=0)),
                ('staff_on_duty', models.PositiveIntegerField(default=0)),
                ('patients_treated', models.PositiveIntegerField(default=0)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='analytics_f_tenant__842981_idx')],
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='submitted', max_length=20)),
                ('patient_age_group', models.CharField(blank=True, max_length=20)),
                ('patient_sex', models.CharField(blank=True, max_length=10)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='catalog.disease')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['tenant', 'status', 'created_at'], name='analytics_i_tenant__d1602f_idx'), models.Index(fields=['tenant', 'diagnosis'], name='analytics_i_tenant__e5cd81_idx')],
            },
        ),
    ]
