# Generated by Django 5.1.4 on 2026-09-02 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_adversedrugreaction_patient_appointment_patient_and_more'),
        ('catalog', '0005_alter_article_tenant_alter_disease_tenant_and_more'),
        ('patients', '0005_patient_merged_into_alter_patient_status_and_more'),
        ('tenants', '0005_seed_nigeria_jurisdiction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_age_group', models.CharField(blank=True, max_length=20)),
                ('patient_sex', models.CharField(blank=True, max_length=10)),
                ('dose', models.CharField(blank=True, max_length=120)),
                ('frequency', models.CharField(blank=True, max_length=120)),
                ('duration_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('prescribed', 'Prescribed'), ('partially_dispensed', 'Partial'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='prescribed', max_length=25)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('case_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='analytics.casereport')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='catalog.medication')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='patients.patient')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['tenant', 'status', 'created_at'], name='analytics_p_tenant__4d041b_idx'), models.Index(fields=['tenant', 'medication'], name='analytics_p_tenant__fa8185_idx')],
            },
        ),
    ]
