# Generated by Django 5.1.4 on 2026-09-04 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_alter_adversedrugreaction_tenant_and_more'),
        ('catalog', '0006_alter_article_tenant_alter_disease_tenant_and_more'),
        ('patients', '0006_alter_patient_tenant_alter_patientaccesslog_tenant'),
        ('tenants', '0006_tenant_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casereport',
            name='source_ref',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='source_ref',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='casereport',
            constraint=models.UniqueConstraint(fields=('tenant', 'source_ref'), name='analytics_case_one_row_per_source'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.UniqueConstraint(fields=('tenant', 'source_ref'), name='analytics_rx_one_row_per_source'),
        ),
    ]
