# Generated by Django 5.1.4 on 2026-09-04 17:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_casereport_source_ref_prescription_source_ref_and_more'),
        ('patients', '0006_alter_patient_tenant_alter_patientaccesslog_tenant'),
        ('tenants', '0006_tenant_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_age_group', models.CharField(blank=True, max_length=20)),
                ('patient_sex', models.CharField(blank=True, max_length=10)),
                ('chief_complaint', models.CharField(max_length=255)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('25')), django.core.validators.MaxValueValidator(Decimal('45'))])),
                ('pulse_bpm', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)])),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(80)])),
                ('systolic_bp', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)])),
                ('diastolic_bp', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)])),
                ('oxygen_saturation', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)])),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('500'))])),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('20')), django.core.validators.MaxValueValidator(Decimal('260'))])),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('disposition', models.CharField(blank=True, choices=[('home', 'Discharged home'), ('follow_up', 'Discharged, follow-up'), ('admitted', 'Admitted'), ('referred', 'Referred out'), ('deceased', 'Died')], max_length=20)),
                ('follow_up_on', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='analytics.appointment')),
                ('case_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='analytics.casereport')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='patients.patient')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['tenant', 'status', 'created_at'], name='analytics_c_tenant__236c70_idx'), models.Index(fields=['tenant', 'disposition'], name='analytics_c_tenant__873431_idx'), models.Index(fields=['patient', 'status'], name='analytics_c_patient_de16ec_idx')],
            },
        ),
    ]
