# Generated by Django 5.1.4 on 2026-09-05 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_consultation'),
        ('catalog', '0006_alter_article_tenant_alter_disease_tenant_and_more'),
        ('patients', '0006_alter_patient_tenant_alter_patientaccesslog_tenant'),
        ('tenants', '0006_tenant_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='group',
            field=models.UUIDField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['tenant', 'group'], name='analytics_p_tenant__9e14a7_idx'),
        ),
    ]
