# Generated by Django 5.1.4 on 2026-09-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0016_casereport_notified_at_casereport_notified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiinteraction',
            name='feedback',
        ),
    ]
