# Generated by Django 5.1.4 on 2026-09-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0018_canonical_region_spellings'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='consultation_category',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
