# Generated by Django 5.1.4 on 2026-09-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0019_consultation_band_on_drug_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='consultation_category',
        ),
    ]
