# Generated by Django 5.1.4 on 2026-10-05 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0020_drop_consultation_band'),
        ('catalog', '0007_disease_notify_immediately'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medication_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='catalog.medication'),
        ),
    ]
