# Generated by Django 5.1.4 on 2026-06-23 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generic_name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(blank=True, max_length=255)),
                ('drug_class', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('indications', models.TextField(blank=True)),
                ('dosage', models.TextField(blank=True)),
                ('side_effects', models.TextField(blank=True)),
                ('warnings', models.TextField(blank=True)),
                ('contraindications', models.TextField(blank=True)),
                ('storage_information', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('medication_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_a', to='catalog.medication')),
                ('medication_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_b', to='catalog.medication')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('icd10_code', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('causes', models.TextField(blank=True)),
                ('risk_factors', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('prevention', models.TextField(blank=True)),
                ('complications', models.TextField(blank=True)),
                ('references', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('medications', models.ManyToManyField(blank=True, related_name='diseases', to='catalog.medication')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('references', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('diseases', models.ManyToManyField(blank=True, related_name='articles', to='catalog.disease')),
                ('medications', models.ManyToManyField(blank=True, related_name='articles', to='catalog.medication')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('indications', models.TextField(blank=True)),
                ('preparation', models.TextField(blank=True)),
                ('risks', models.TextField(blank=True)),
                ('recovery', models.TextField(blank=True)),
                ('references', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('diseases', models.ManyToManyField(blank=True, related_name='procedures', to='catalog.disease')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('diseases', models.ManyToManyField(blank=True, related_name='specialties', to='catalog.disease')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity_level', models.PositiveSmallIntegerField(default=1)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.ManyToManyField(blank=True, related_name='diseases', to='catalog.symptom'),
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('purpose', models.TextField(blank=True)),
                ('preparation', models.TextField(blank=True)),
                ('normal_range', models.CharField(blank=True, max_length=255)),
                ('units', models.CharField(blank=True, max_length=50)),
                ('references', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('diseases', models.ManyToManyField(blank=True, related_name='lab_tests', to='catalog.disease')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'name'], name='catalog_lab_tenant__80b801_idx')],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['tenant', 'generic_name'], name='catalog_med_tenant__4f5452_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='druginteraction',
            unique_together={('tenant', 'medication_a', 'medication_b')},
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['tenant', 'title'], name='catalog_art_tenant__56daf4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['tenant', 'name'], name='catalog_pro_tenant__18127d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='procedure',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AddIndex(
            model_name='specialty',
            index=models.Index(fields=['tenant', 'name'], name='catalog_spe_tenant__59fad6_idx'),
        ),
        migrations.AddIndex(
            model_name='symptom',
            index=models.Index(fields=['tenant', 'name'], name='catalog_sym_tenant__51b898_idx'),
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['tenant', 'name'], name='catalog_dis_tenant__2bd4ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='disease',
            unique_together={('tenant', 'slug')},
        ),
    ]
