# Generated by Django 5.1.4 on 2026-06-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_drop_fts_gin_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='notifiable',
            field=models.BooleanField(default=False),
        ),
    ]
