# Generated by Django 5.1.4 on 2026-09-04 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0005_seed_nigeria_jurisdiction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive branches are hidden from the app; their data stays.')),
                ('is_main', models.BooleanField(default=False, help_text='The head-office branch. One per tenant.')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'branches',
                'ordering': ('-is_main', 'name', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('tenant',), name='one_main_branch_per_tenant')],
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
