# Generated by Django 5.1.4 on 2026-10-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_latitude_branch_longitude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
