# Generated by Django 5.1.4 on 2026-09-04 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('analytics', '0001_initial'),
        ('inventory', '0001_initial'),
        ('patients', '0001_initial'),
        ('pharmacy', '0004_tillsession_salepayment_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='TillSession',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                        ('opening_float', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('counted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                        ('closed_at', models.DateTimeField(blank=True, null=True)),
                        ('notes', models.TextField(blank=True)),
                        ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='till_sessions', to=settings.AUTH_USER_MODEL)),
                        ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                    ],
                    options={
                        'ordering': ('-created_at', '-id'),
                        'indexes': [models.Index(fields=['tenant', 'status'], name='pharmacy_ti_tenant__c6ece5_idx')],
                        'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('tenant', 'opened_by'), name='one_open_till_per_cashier')],
                        'db_table': 'pharmacy_tillsession',
                    },
                ),
                migrations.CreateModel(
                    name='Sale',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('reference', models.CharField(max_length=30)),
                        ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Transfer'), ('hmo', 'Hmo')], default='cash', max_length=20)),
                        ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                        ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('patient_payable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('hmo_payable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('notes', models.TextField(blank=True)),
                        ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='pharmacy.hmoenrollment')),
                        ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_sales', to='patients.patient')),
                        ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_sales', to='analytics.prescription')),
                        ('served_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_sales', to=settings.AUTH_USER_MODEL)),
                        ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                        ('amount_tendered', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                    ],
                    options={
                        'ordering': ('-created_at', '-id'),
                        'indexes': [models.Index(fields=['tenant', 'created_at'], name='pharmacy_sa_tenant__49973c_idx'), models.Index(fields=['tenant', 'status'], name='pharmacy_sa_tenant__f95a5b_idx'), models.Index(fields=['tenant', 'payment_method'], name='pharmacy_sa_tenant__ab045a_idx')],
                        'constraints': [],
                        'unique_together': {('tenant', 'reference')},
                        'db_table': 'pharmacy_sale',
                    },
                ),
                migrations.CreateModel(
                    name='SaleItem',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('quantity', models.PositiveIntegerField(default=1)),
                        ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.sale')),
                        ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                        ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_lines', to='inventory.stockbatch')),
                        ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='inventory.stockitem')),
                    ],
                    options={
                        'ordering': ('id',),
                        'indexes': [models.Index(fields=['tenant', 'item'], name='pharmacy_sa_tenant__c2eaa2_idx')],
                        'constraints': [],
                        'db_table': 'pharmacy_saleitem',
                    },
                ),
                migrations.CreateModel(
                    name='SalePayment',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Transfer')], default='cash', max_length=20)),
                        ('tendered', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('applied', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('change', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.sale')),
                        ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_payments', to=settings.AUTH_USER_MODEL)),
                        ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                        ('till_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='pos.tillsession')),
                    ],
                    options={
                        'ordering': ('created_at', 'id'),
                        'indexes': [models.Index(fields=['tenant', 'till_session'], name='pharmacy_sa_tenant__b4cc8f_idx')],
                        'constraints': [],
                        'db_table': 'pharmacy_salepayment',
                    },
                ),
                migrations.CreateModel(
                    name='PurchaseOrder',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('reference', models.CharField(max_length=30)),
                        ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('partial', 'Partial'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                        ('expected_date', models.DateField(blank=True, null=True)),
                        ('notes', models.TextField(blank=True)),
                        ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to=settings.AUTH_USER_MODEL)),
                        ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                        ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.supplier')),
                    ],
                    options={
                        'ordering': ('-created_at', '-id'),
                        'indexes': [models.Index(fields=['tenant', 'status', 'created_at'], name='pharmacy_pu_tenant__764fe8_idx'), models.Index(fields=['tenant', 'supplier'], name='pharmacy_pu_tenant__55457a_idx')],
                        'constraints': [],
                        'unique_together': {('tenant', 'reference')},
                        'db_table': 'pharmacy_purchaseorder',
                    },
                ),
                migrations.CreateModel(
                    name='PurchaseOrderLine',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('quantity_ordered', models.PositiveIntegerField(default=1)),
                        ('quantity_received', models.PositiveIntegerField(default=0)),
                        ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.purchaseorder')),
                        ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                        ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='inventory.stockitem')),
                    ],
                    options={
                        'ordering': ('id',),
                        'indexes': [models.Index(fields=['tenant', 'item'], name='pharmacy_pu_tenant__a18d4b_idx')],
                        'constraints': [],
                        'unique_together': {('order', 'item')},
                        'db_table': 'pharmacy_purchaseorderline',
                    },
                ),
            ],
        ),
    ]
