# Generated by Django 5.1.4 on 2026-09-04 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_alter_adversedrugreaction_tenant_and_more'),
        ('branches', '0001_initial'),
        ('customers', '0002_initial'),
        ('inventory', '0003_stockcheck_stockcheckitem_transferrequest_and_more'),
        ('patients', '0006_alter_patient_tenant_alter_patientaccesslog_tenant'),
        ('pharmacy', '0006_alter_claimbatch_options_alter_claim_tenant_and_more'),
        ('pos', '0002_cashier_dispensinglog_expense_expensecategory_and_more'),
        ('prescriptions', '0001_initial'),
        ('tenants', '0005_seed_nigeria_jurisdiction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='rx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='prescriptions.prescription'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='brand',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='form',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='return_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tillsession',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='till_sessions', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card / POS'), ('transfer', 'Transfer'), ('wallet', 'Wallet'), ('hmo', 'Hmo'), ('split', 'Split')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('credit', 'Credit'), ('partial_return', 'Partial Return'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card / POS'), ('transfer', 'Transfer'), ('wallet', 'Wallet')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='tillsession',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='cashier',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='cashier',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='pos.cashier'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'is_wholesale'], name='pharmacy_sa_tenant__a92c27_idx'),
        ),
        migrations.AddField(
            model_name='dispensinglog',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensing_logs', to='inventory.stockitem'),
        ),
        migrations.AddField(
            model_name='dispensinglog',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensing_logs', to='pos.sale'),
        ),
        migrations.AddField(
            model_name='dispensinglog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='dispensinglog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensing_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='expense',
            name='till_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='pos.tillsession'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='pos.expensecategory'),
        ),
        migrations.AddField(
            model_name='notification',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='inventory.stockitem'),
        ),
        migrations.AddField(
            model_name='notification',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='pos.cashier'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='dispenser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='pos.sale'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='paymentrequestitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_request_lines', to='inventory.stockitem'),
        ),
        migrations.AddField(
            model_name='paymentrequestitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.paymentrequest'),
        ),
        migrations.AddField(
            model_name='paymentrequestitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='pos.saleitem'),
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='pos.sale'),
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='cashier',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='dispensinglog',
            index=models.Index(fields=['tenant', 'created_at'], name='pos_dispens_tenant__75030a_idx'),
        ),
        migrations.AddIndex(
            model_name='dispensinglog',
            index=models.Index(fields=['tenant', 'item'], name='pos_dispens_tenant__1ee0c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'date'], name='pos_expense_tenant__9f8001_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'payment_source'], name='pos_expense_tenant__ce63d4_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'user', 'is_read'], name='pos_notific_tenant__486153_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='pos_payment_tenant__1dd871_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentrequest',
            unique_together={('tenant', 'reference')},
        ),
        migrations.AddIndex(
            model_name='paymentrequestitem',
            index=models.Index(fields=['tenant', 'item'], name='pos_payment_tenant__d1a31f_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrecord',
            index=models.Index(fields=['tenant', 'created_at'], name='pos_returnr_tenant__15b173_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrecord',
            index=models.Index(fields=['tenant', 'refund_method'], name='pos_returnr_tenant__9191ed_idx'),
        ),
    ]
