# Generated by Django 5.1.4 on 2026-09-06 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_hmo_preauth_threshold_hmoenrollment_annual_limit_and_more'),
        ('pos', '0003_sale_rx_saleitem_barcode_saleitem_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='authorization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='pharmacy.preauthorization'),
        ),
    ]
