# Generated by Django 5.1.4 on 2026-09-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_sale_authorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='receipt_kept_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='receipt_printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
