# Generated by Django 5.1.4 on 2026-09-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_sale_receipt_kept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='consultation_fee',
        ),
    ]
